export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
export const PREFERENCES_SUCCESS = 'PREFERENCES_SUCCESS';
